//! Embedded frontend assets.
//!
//! Every byte the browser loads — the Datastar JS runtime, the Pico CSS theme,
//! the thin custom stylesheet, and the favicon/logo — is vendored into the
//! repository under `assets/` and compiled into the binary via
//! [`include_bytes!`].  There are **no** CDN fetches at runtime and no Node
//! build step (SPEC §9).
//!
//! # Pinned versions
//!
//! The vendored Datastar JS **must** stay on the same major/API version as the
//! `datastar` Rust crate (SPEC: E8.1), because the SSE UI (E8.6) speaks the v1
//! `PatchElements` / `PatchSignals` protocol that both sides implement.  The
//! pinned versions are recorded here next to the assets so SDK ↔ asset drift
//! is visible in one place:
//!
//! | Asset | Upstream version | Rust counterpart |
//! |---|---|---|
//! | `datastar.js` | [`DATASTAR_VERSION`] (`1.0.1`) | `datastar` crate `0.3.x` (v1 protocol) |
//! | `pico.pumpkin.min.css` | [`PICO_VERSION`] (`2.1.1`, [`PICO_PRESET`]) | — |
//! | `/assets/icons.svg` (Lucide sprite) | [`ICONDATA_LU_VERSION`](super::icons::ICONDATA_LU_VERSION) | `icondata_lu` crate (generated by [`super::icons`]) |
//!
//! Fingerprinted assets (`/assets/app.css?v=…`, etc.) are served with a long,
//! immutable `Cache-Control`; the `?v=` token busts the cache on upgrade.  The
//! icon sprite (`/assets/icons.svg`) is referenced by the `icon` macro without
//! a `?v=` token, so it is instead served with `ETag` revalidation
//! ([`Assets::serve_revalidatable`]) — otherwise `immutable` would pin a stale
//! sprite and a newly-added icon would never reach a returning browser.

use std::sync::LazyLock;

use axum::{
    http::{HeaderMap, HeaderValue, StatusCode, header},
    response::{IntoResponse, Response},
};

// ── Pinned upstream versions ────────────────────────────────────────────────

/// Vendored Datastar JS bundle version (`assets/datastar.js`).
///
/// Keep in lockstep with the `datastar` crate's protocol version.
pub const DATASTAR_VERSION: &str = "1.0.1";

/// Vendored Pico CSS version (`assets/pico.pumpkin.min.css`).
pub const PICO_VERSION: &str = "2.1.1";

/// The Pico CSS colour preset in use — chosen to match the logo's warm orange.
pub const PICO_PRESET: &str = "pumpkin";

// ── Embedded bytes ──────────────────────────────────────────────────────────

const DATASTAR_JS: &[u8] = include_bytes!("../../assets/datastar.js");
const PICO_CSS: &[u8] = include_bytes!("../../assets/pico.pumpkin.min.css");
const APP_CSS: &[u8] = include_bytes!("../../assets/app.css");
const ICON_PNG: &[u8] = include_bytes!("../../assets/icon.png");

/// `Cache-Control` for assets served at a **fingerprinted** URL (`?v=…`).  The
/// content at a given URL is fixed for the lifetime of the build, so we allow
/// long-lived immutable caching; the `?v=` token changes the URL on upgrade.
const IMMUTABLE: &str = "public, max-age=31536000, immutable";

/// `Cache-Control` for assets served at a **stable, un-fingerprinted** URL — the
/// icon sprite (`/assets/icons.svg`), which the `icon` askama macro references
/// without a `?v=` token (it has no access to the fingerprint).  `no-cache`
/// lets the browser store it but forces an `ETag` revalidation before reuse, so
/// a newly-added icon reaches a browser that cached a prior build instead of
/// being pinned for a year by `immutable`.
const REVALIDATE: &str = "no-cache";

/// Short content fingerprint of the embedded frontend assets, appended to asset
/// URLs as a `?v=` cache-busting token.
///
/// Because assets are served `immutable` at stable paths (`/assets/app.css`,
/// …), a browser that cached one build keeps it across an upgrade — so a new
/// stylesheet rule would never reach it.  Hashing the asset bytes makes the
/// token change exactly when any asset's content does, which changes the URL
/// and forces a fresh fetch on upgrade while preserving immutable caching
/// within a build.
static FINGERPRINT: LazyLock<String> = LazyLock::new(|| {
    use std::hash::{Hash, Hasher};

    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    for asset in [DATASTAR_JS, PICO_CSS, APP_CSS, ICON_PNG] {
        asset.hash(&mut hasher);
    }
    super::icons::Icons::sprite_bytes().hash(&mut hasher);
    format!("{:016x}", hasher.finish())
});

// ── Assets handler namespace ────────────────────────────────────────────────

/// Namespace for the static-asset route handlers.
///
/// Implemented as associated functions on a unit struct (rather than free
/// functions) per the repository convention that behaviour lives on types.
pub struct Assets;

impl Assets {
    /// Cache-busting token for asset URLs (see [`FINGERPRINT`]).
    pub fn fingerprint() -> &'static str {
        &FINGERPRINT
    }

    /// `GET /assets/datastar.js` — the Datastar JS runtime.
    pub async fn datastar_js() -> Response {
        Self::serve(DATASTAR_JS, "text/javascript; charset=utf-8")
    }

    /// `GET /assets/pico.pumpkin.min.css` — the Pico CSS theme.
    pub async fn pico_css() -> Response {
        Self::serve(PICO_CSS, "text/css; charset=utf-8")
    }

    /// `GET /assets/app.css` — the thin custom stylesheet.
    pub async fn app_css() -> Response {
        Self::serve(APP_CSS, "text/css; charset=utf-8")
    }

    /// `GET /assets/icon.png` (and `/favicon.ico`) — the logo / favicon.
    pub async fn icon_png() -> Response {
        Self::serve(ICON_PNG, "image/png")
    }

    /// Build a cacheable response for a static byte slice with a fixed
    /// content type.
    ///
    /// Shared with the generated icon sprite (`super::icons`) so every vendored
    /// asset gets identical immutable-cache headers from one place.
    pub(crate) fn serve(body: &'static [u8], content_type: &'static str) -> Response {
        (
            [
                (header::CONTENT_TYPE, HeaderValue::from_static(content_type)),
                (header::CACHE_CONTROL, HeaderValue::from_static(IMMUTABLE)),
            ],
            body,
        )
            .into_response()
    }

    /// Build a **revalidatable** response for an asset served at a stable path
    /// with no `?v=` cache-buster (the icon sprite).
    ///
    /// The response carries a content `ETag` and `Cache-Control: no-cache`.  If
    /// the request's `If-None-Match` already matches the current `etag`, answer
    /// **304** with no body; otherwise return the asset.  This lets a browser
    /// keep its cached copy across page loads (a cheap 304) while still picking
    /// up a changed sprite on the next build — unlike `immutable`, which would
    /// pin a stale sprite (see [`REVALIDATE`]).
    pub(crate) fn serve_revalidatable(
        req_headers: &HeaderMap,
        body: &'static [u8],
        content_type: &'static str,
        etag: &'static str,
    ) -> Response {
        let cache = HeaderValue::from_static(REVALIDATE);
        let etag_val = HeaderValue::from_static(etag);

        if req_headers
            .get(header::IF_NONE_MATCH)
            .and_then(|v| v.to_str().ok())
            .is_some_and(|inm| if_none_match_satisfied(inm, etag))
        {
            return (
                StatusCode::NOT_MODIFIED,
                [(header::ETAG, etag_val), (header::CACHE_CONTROL, cache)],
            )
                .into_response();
        }

        (
            [
                (header::CONTENT_TYPE, HeaderValue::from_static(content_type)),
                (header::CACHE_CONTROL, cache),
                (header::ETAG, etag_val),
            ],
            body,
        )
            .into_response()
    }
}

/// Whether an `If-None-Match` header value matches `etag`.
///
/// Handles the comma-separated list, the `*` wildcard, and the weak-validator
/// `W/` prefix that [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110#name-if-none-match)
/// permits; `etag` is our own strong, quoted tag.
fn if_none_match_satisfied(header: &str, etag: &str) -> bool {
    header.split(',').any(|tag| {
        let tag = tag.trim().trim_start_matches("W/");
        tag == "*" || tag == etag
    })
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use axum::http::StatusCode;

    #[test]
    fn assets_are_non_empty() {
        assert!(!DATASTAR_JS.is_empty(), "datastar.js must be embedded");
        assert!(!PICO_CSS.is_empty(), "pico css must be embedded");
        assert!(!APP_CSS.is_empty(), "app.css must be embedded");
        assert!(!ICON_PNG.is_empty(), "icon.png must be embedded");
    }

    #[test]
    fn datastar_asset_matches_pinned_version() {
        // The vendored bundle starts with a `// Datastar vX.Y.Z` banner; guard
        // that it matches the version we claim so an accidental re-vendor of a
        // different version is caught.
        let head = std::str::from_utf8(&DATASTAR_JS[..64]).unwrap_or("");
        assert!(
            head.contains(DATASTAR_VERSION),
            "datastar.js banner must contain {DATASTAR_VERSION}, got: {head:?}"
        );
    }

    #[test]
    fn pico_asset_matches_pinned_version() {
        let head = std::str::from_utf8(&PICO_CSS[..160]).unwrap_or("");
        assert!(
            head.contains(PICO_VERSION),
            "pico css banner must contain {PICO_VERSION}"
        );
    }

    #[tokio::test]
    async fn serve_sets_content_type_and_cache_headers() {
        let resp = Assets::app_css().await;
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(
            resp.headers().get(header::CONTENT_TYPE).unwrap(),
            "text/css; charset=utf-8"
        );
        assert_eq!(
            resp.headers().get(header::CACHE_CONTROL).unwrap(),
            IMMUTABLE
        );
    }

    #[test]
    fn if_none_match_handles_list_weak_and_wildcard() {
        assert!(if_none_match_satisfied("\"abc\"", "\"abc\""));
        assert!(if_none_match_satisfied("W/\"abc\"", "\"abc\""));
        assert!(if_none_match_satisfied("*", "\"abc\""));
        assert!(if_none_match_satisfied("\"x\", \"abc\", \"y\"", "\"abc\""));
        assert!(!if_none_match_satisfied("\"other\"", "\"abc\""));
        assert!(!if_none_match_satisfied("", "\"abc\""));
    }
}
